<?php

namespace App\Filament\Resources;

use App\Enums\DocumentType;
use App\Enums\UserRole;
use App\Filament\Resources\GeneratedDocumentResource\Pages;
use App\Models\GeneratedDocument;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class GeneratedDocumentResource extends Resource
{
    protected static ?string $model = GeneratedDocument::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-arrow-down';

    protected static ?string $navigationLabel = 'Generated PDFs';

    protected static ?string $navigationGroup = 'Documents';

    public static function getEloquentQuery(): Builder
    {
        /** @var Builder<GeneratedDocument> $query */
        $query = parent::getEloquentQuery();
        $user = auth()->user();

        if ($user === null || $user->role === UserRole::Admin) {
            return $query;
        }

        if ($user->role === UserRole::SiteEngineer) {
            return $query->where(function (Builder $q) use ($user): void {
                $q->whereHas('dailyReport.site.project.engineers', fn (Builder $e) => $e->whereKey($user->id))
                    ->orWhereHas('project.engineers', fn (Builder $e) => $e->whereKey($user->id));
            });
        }

        return $query->whereRaw('1 = 0');
    }

    public static function form(Form $form): Form
    {
        return $form->schema([]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('created_at', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('document_type')
                    ->label('Document')
                    ->badge()
                    ->color(fn (DocumentType $state): string => match ($state) {
                        DocumentType::DailyProgress => 'primary',
                        DocumentType::WeeklyDigest => 'info',
                        DocumentType::AttendanceRoster => 'success',
                    })
                    ->formatStateUsing(fn (DocumentType $state): string => $state->label()),
                Tables\Columns\TextColumn::make('subject')
                    ->label('Subject')
                    ->getStateUsing(function (GeneratedDocument $record): string {
                        $report = $record->dailyReport;
                        if ($report !== null) {
                            return $report->site->name;
                        }

                        $project = $record->project;

                        return $project !== null ? $project->name : '—';
                    }),
                Tables\Columns\TextColumn::make('generatedBy.name')
                    ->label('Generated By')
                    ->placeholder('—'),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Generated At')
                    ->dateTime('Y-m-d H:i')
                    ->sortable(),
            ])
            ->actions([
                Tables\Actions\Action::make('download')
                    ->label('Download')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->url(fn (GeneratedDocument $record): string => route('generated-documents.download', $record))
                    ->openUrlInNewTab(),
            ])
            ->bulkActions([]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListGeneratedDocuments::route('/'),
        ];
    }
}
