<?php

namespace App\Filament\Resources;

use App\Enums\PayrollRunStatus;
use App\Filament\Resources\PayrollRunResource\Pages;
use App\Filament\Resources\PayrollRunResource\RelationManagers\PayrollItemsRelationManager;
use App\Models\PayrollRun;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class PayrollRunResource extends Resource
{
    protected static ?string $model = PayrollRun::class;

    protected static ?string $navigationIcon = 'heroicon-o-banknotes';

    protected static ?string $navigationLabel = 'Payroll Runs';

    protected static ?string $navigationGroup = 'Finance';

    protected static ?int $navigationSort = 1;

    public static function form(Form $form): Form
    {
        return $form->schema([
            DatePicker::make('period_start')->disabled(),
            DatePicker::make('period_end')->disabled(),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('period_start', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('period_start')
                    ->date('Y-m-d')
                    ->sortable(),
                Tables\Columns\TextColumn::make('period_end')
                    ->date('Y-m-d')
                    ->sortable(),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (PayrollRunStatus $state): string => match ($state) {
                        PayrollRunStatus::Draft => 'gray',
                        PayrollRunStatus::PendingReview => 'warning',
                        PayrollRunStatus::Approved => 'success',
                        PayrollRunStatus::Paid => 'info',
                    })
                    ->formatStateUsing(fn (PayrollRunStatus $state): string => $state->label()),
                Tables\Columns\TextColumn::make('items_count')
                    ->counts('items')
                    ->label('Workers'),
                Tables\Columns\TextColumn::make('items_sum_total_pay')
                    ->sum('items', 'total_pay')
                    ->label('Total Pay')
                    ->money('IDR'),
                Tables\Columns\TextColumn::make('generatedBy.name')
                    ->label('Generated By')
                    ->placeholder('System')
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('approvedBy.name')
                    ->label('Approved By')
                    ->placeholder('—')
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->options(PayrollRunStatus::class),
            ])
            ->actions([
                Tables\Actions\Action::make('submit_for_review')
                    ->label('Submit for Review')
                    ->icon('heroicon-o-arrow-up-circle')
                    ->color('warning')
                    ->requiresConfirmation()
                    ->visible(fn (PayrollRun $record): bool => auth()->user()?->can('submitForReview', $record) ?? false)
                    ->action(function (PayrollRun $record): void {
                        $record->submitForReview(auth()->user());

                        Notification::make()->title('Payroll run submitted for review.')->success()->send();
                    }),
                Tables\Actions\Action::make('approve')
                    ->icon('heroicon-o-check-circle')
                    ->color('success')
                    ->requiresConfirmation()
                    ->visible(fn (PayrollRun $record): bool => auth()->user()?->can('approve', $record) ?? false)
                    ->action(function (PayrollRun $record): void {
                        $record->approve(auth()->user());

                        Notification::make()->title('Payroll run approved.')->success()->send();
                    }),
                Tables\Actions\Action::make('mark_paid')
                    ->label('Mark Paid')
                    ->icon('heroicon-o-currency-dollar')
                    ->color('info')
                    ->requiresConfirmation()
                    ->visible(fn (PayrollRun $record): bool => auth()->user()?->can('markPaid', $record) ?? false)
                    ->action(function (PayrollRun $record): void {
                        $record->markPaid(auth()->user());

                        Notification::make()->title('Payroll run marked as paid.')->success()->send();
                    }),
                Tables\Actions\ViewAction::make(),
            ])
            ->bulkActions([]);
    }

    public static function getRelations(): array
    {
        return [
            PayrollItemsRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPayrollRuns::route('/'),
            'view' => Pages\ViewPayrollRun::route('/{record}'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        /** @var Builder<PayrollRun> $query */
        $query = parent::getEloquentQuery();

        return $query->with(['generatedBy', 'approvedBy']);
    }
}
